### ISSUE TITLE
小细节问题

### ISSUE THREAD

**Issue by xiaohangDAD** [Arasple/TrChat#12]
![图片](https://user-images.githubusercontent.com/41426821/69908602-27f77e80-1428-11ea-84f1-3a5e45079f33.png)
```
  shareBilibili:
    pattern: 'av( )?[1-9]([0-9]{0,9})'
    text-filter: '[1-9]([0-9]{0,9})'
    # 自定义显示 JSON 组件
    display:
      text: '&8[&f&lBilibili&8]'
      hover:
        - ''
        - '&7这可能是一个 Bilibili 视频,'
        - '&7点击即可访问'
        - ''
        - '&3Av号: &b{0}}'
      url: 'https://www.bilibili.com/video/av{0}'
```
这个"        - '&3Av号: &b{0}}'"多打了一个"}"
