### ISSUE TITLE
Color code permissions doesn't seem to work

### ISSUE THREAD

**Issue by HgeX** [Arasple/TrChat#24]
This is how my `formats.yml` file looks like *(well, a part of it)*

```yaml
NORMAL:
  # Requirement to use this format, for example: 'player.isOp()'
  - requirement: null

    # Message part
    msg:
      # Default chat color
      # (when the player doesn't have any permission of trchat.color.force-defaultcolor.<CODE>)
      default-color: 'f'
      hover: '❀ &7Elküldve ekkor: &6%server_time_HH:mm:ss%'

    # Custom Json Format Parts (Before Message Part)
    parts:
      world:
        text: ''
        hover: ''
        command: ''
        # (Optional) Requirement to display this JSON part for the player
        requirement: null
      part-before-player:
        text: ' '
      player:
        text: '%luckperms_prefix%%player_name%'
        hover: |-
          ❀ &7Verzió: &6%viaversion_player_protocol_version%&r
          ❀ &7Ping: %player_colored_ping% ms&r
          ❀ &7Játékidő &o(%server_name%)&7: &6%statistic_time_played%
          &r
          &8➽ &fKattints privát üzenet küldéséhez!
        suggest: '/msg %player_name% '
      part-before-msg:
        text: ' &7► '
```
The issue is, even though some players have the permission `trchat.color.force-defaultcolor.<CODE>` to true (of course `<CODE>` is always replaced to match the chatcolor), their chatcolor is still thet default for some reason.
